### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by T-ryunosuke** [T-ryunosuke/develop_best#8]
■Webアプリの概要
ユーザーがbestと感じた「モノ」・「場所」・「体験」などをカテゴリー別に投稿してもらい、それを他のユーザーと共有することができるSNSよりのレビューアプリです。 
投稿にはテキストだけでなく、画像も添付可能です。
自分と好みや趣味の合うユーザーをフォローしておいたり、投稿に対しても「いいね」やコメントで反応をすることができます。
また自分が気になるワードで投稿の検索をすることもでき、興味のある事柄について他のユーザーはどのようなbestを利用・経験しているのかを簡単に調べることも可能です。
プロフィールを設定することもできるため、そこで自身を少しでも知ってもらうことで、他ユーザーからのあなたの投稿に対する信用を向上させることもあります。

■ProjectsのURL
https://github.com/users/T-ryunosuke/projects/1/views/1

■MVPリリースまで
- [ ] docker準備
- [ ] rails new
- [ ] Renderにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン/ログアウト機能
- [ ] カテゴリー登録機能
- [ ] 投稿作成機能
- [ ] 投稿一覧機能
- [ ] 投稿削除機能
- [ ] 投稿編集機能
- [ ] ページネーション機能
- [ ] いいね機能
- [ ] コメント作成機能
- [ ] コメント削除機能
- [ ] フォロー/フォロワー機能
- [ ] プロフィール機能
- [ ] 投稿検索機能

■MVP後
- [ ] xへのシェア機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] オートコンプリート検索機能

■MVPレビュー依頼予定日
予定日：2024年 9月 30日

**Comment by beppumasaki** [comment]
概ね良いかと思います。LGTMです。
